name: Test

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: DevExpress/testcafe-build-system/actions/prepare@main
        with:
          node-version: 'latest'

      - run: npm ci --legacy-peer-deps

      - run: npm run test